"""
Django settings for clinic_platform project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import importlib.util
from urllib.parse import parse_qs, unquote, urlparse
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read the .env file if it exists (optional)
ENV_FILE_PATH = BASE_DIR / '.env'
if ENV_FILE_PATH.exists():
    load_dotenv(str(ENV_FILE_PATH))

# Helper to get env vars with optional defaults and bool parsing
def getenv(key, default=None):
    return os.environ.get(key, default)

def getbool(key, default=False):
    val = os.environ.get(key)
    if val is None:
        return default
    return str(val).lower() in ('1', 'true', 'yes')


def _first_env(*keys: str) -> str | None:
    """Return the first non-empty environment value among provided keys."""
    for key in keys:
        value = os.environ.get(key)
        if value is not None and str(value).strip() != '':
            return value
    return None


def _db_from_url(url: str | None) -> dict:
    """Parse a Postgres DATABASE_URL into Django DATABASES fields."""
    if not url:
        return {}

    parsed = urlparse(url)
    if parsed.scheme not in ('postgres', 'postgresql', 'psql'):
        return {}

    cfg = {
        'NAME': unquote((parsed.path or '').lstrip('/')) or None,
        'USER': unquote(parsed.username) if parsed.username else None,
        'PASSWORD': unquote(parsed.password) if parsed.password else None,
        'HOST': parsed.hostname,
        'PORT': str(parsed.port) if parsed.port else None,
    }

    query = parse_qs(parsed.query)
    sslmode = (query.get('sslmode') or [None])[-1]
    if sslmode:
        cfg['OPTIONS'] = {'sslmode': sslmode}

    return cfg


def _resolved_db_config(prefix: str, fallback_url_env: str = 'DATABASE_URL', fallback: dict | None = None) -> dict:
    """Resolve DB settings from explicit vars, then URL vars, then fallback config."""
    explicit = {
        'NAME': getenv(f'{prefix}_NAME'),
        'USER': getenv(f'{prefix}_USER'),
        'PASSWORD': getenv(f'{prefix}_PASSWORD'),
        'HOST': getenv(f'{prefix}_HOST'),
        'PORT': getenv(f'{prefix}_PORT'),
    }

    public_url_cfg = _db_from_url(
        getenv(f'{prefix}_DATABASE_PUBLIC_URL')
        or getenv(f'{prefix}_PUBLIC_URL')
        or getenv('DATABASE_PUBLIC_URL')
        or getenv('DATABASE_PULIC_URL')
    )

    url_cfg = public_url_cfg or _db_from_url(
        getenv(f'{prefix}_DATABASE_URL')
        or getenv(f'{prefix}_URL')
        or getenv(fallback_url_env)
    )

    # Railway/managed Postgres environments may expose credentials as PG* or POSTGRES_*.
    generic_pg = {
        'NAME': _first_env('PGDATABASE', 'POSTGRES_DB'),
        'USER': _first_env('PGUSER', 'POSTGRES_USER'),
        'PASSWORD': _first_env('PGPASSWORD', 'POSTGRES_PASSWORD'),
        'HOST': _first_env('PGHOST', 'POSTGRES_HOST'),
        'PORT': _first_env('PGPORT', 'POSTGRES_PORT'),
    }

    merged = {'ENGINE': 'django.db.backends.postgresql'}
    base = fallback or {}
    for key in ('NAME', 'USER', 'PASSWORD', 'HOST', 'PORT'):
        merged[key] = explicit.get(key) or url_cfg.get(key) or generic_pg.get(key) or base.get(key)

    options = url_cfg.get('OPTIONS') or base.get('OPTIONS')
    if options:
        merged['OPTIONS'] = options

    return merged

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vw6c0!zy1jhtdgjk@x-qlrrlyak@3uuip6xcu23)axytyx)q_u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getbool('DEBUG', False)

ALLOWED_HOSTS = [
    host.strip()
    for host in getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,.railway.app').split(',')
    if host.strip()
]

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',

    # Microservice apps
    'users.apps.UsersConfig',
    'doctors.apps.DoctorsConfig',
    'patients.apps.PatientsConfig',
    'schedules.apps.SchedulesConfig',
    'bookings.apps.BookingsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'clinic_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clinic_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        **_resolved_db_config('USER_DB', fallback_url_env='DATABASE_URL'),
        'TEST': {
            'MIRROR': 'user_db',
        },
    },
    'user_db': {
        **_resolved_db_config('USER_DB', fallback_url_env='DATABASE_URL'),
        'TEST': {
            'DEPENDENCIES': [],
        },
    },
    'booking_db': {
        **_resolved_db_config(
            'BOOKING_DB',
            fallback_url_env='BOOKING_DATABASE_URL',
            fallback=_resolved_db_config('USER_DB', fallback_url_env='DATABASE_URL'),
        ),
        'TEST': {
            'DEPENDENCIES': ['user_db'],
        },
    },
}

# In some CI setups both aliases intentionally point to the same physical DB.
# Django test database ordering treats alias dependencies as circular in that case,
# so only enforce booking_db -> user_db dependency when databases are distinct.
_same_test_db_signature = (
    DATABASES['user_db']['ENGINE'] == DATABASES['booking_db']['ENGINE']
    and DATABASES['user_db']['HOST'] == DATABASES['booking_db']['HOST']
    and str(DATABASES['user_db']['PORT']) == str(DATABASES['booking_db']['PORT'])
    and DATABASES['user_db']['NAME'] == DATABASES['booking_db']['NAME']
)
if _same_test_db_signature:
    DATABASES['booking_db']['TEST']['DEPENDENCIES'] = []

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Register the database routers
DATABASE_ROUTERS = ['clinic_platform.router.MicroserviceDatabaseRouter']

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': int(getenv('API_PAGE_SIZE', '20')),
}

CACHE_TTL_SECONDS = int(getenv('CACHE_TTL_SECONDS', '60'))
REDIS_URL = (getenv('REDIS_URL', '') or '').strip()
USE_REDIS_CACHE = getbool('USE_REDIS_CACHE', bool(REDIS_URL))
REDIS_PY_AVAILABLE = importlib.util.find_spec('redis') is not None

if USE_REDIS_CACHE and REDIS_URL and REDIS_PY_AVAILABLE:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': CACHE_TTL_SECONDS,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'clinic-platform-cache',
            'TIMEOUT': CACHE_TTL_SECONDS,
        }
    }

SIMPLE_JWT = {
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
    'ACCESS_TOKEN_LIFETIME': timedelta(days=int(getenv('JWT_ACCESS_EXPIRATION_DAYS', '1'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(getenv('JWT_REFRESH_EXPIRATION_DAYS', '7'))),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CareConnect API',
    'DESCRIPTION': (
        'CareConnect clinic booking API for user account and scheduling services.\n\n'
        '## Quick Start\n'
        '1. Open `/api/docs/` to explore endpoints interactively.\n'
        '2. Register or sign in using the user auth endpoints.\n'
        '3. Obtain JWT access and refresh tokens from the auth login endpoint.\n'
        '4. Click **Authorize** in Swagger and enter: `Bearer <access_token>`.\n'
        '5. Call protected endpoints under users, doctors, patients, schedules, and appointments.\n\n'
        '## Useful URLs\n'
        '- API Index: `/`\n'
        '- Swagger UI: `/api/docs/`\n'
        '- OpenAPI Schema: `/api/schema/`\n'
        '- ReDoc: `/api/redoc/`\n'
        '- Admin: `/admin/`\n'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY_SCHEMES': {
        'credentialsAuth': {
            'type': 'oauth2',
            'flows': {
                'password': {
                    'tokenUrl': '/api/users/swagger-login/',
                    'scopes': {},
                }
            }
        }
    },
    'SECURITY': [{'credentialsAuth': []}],
}


# LOGGING SETTINGS
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'simple': {
        'format': '{levelname} {message}',
        'style': '{',
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'django.log',
            'formatter': 'verbose',
        },
    },

    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },

    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'myapp': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}