# Generated by Django 6.0.7 on 2026-07-15 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_backfill_and_relax_doctor_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(help_text='Date this working schedule applies to.')),
                ('start_time', models.TimeField(help_text='Schedule start time for the day.')),
                ('end_time', models.TimeField(help_text='Schedule end time for the day.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'db_table': 'doctor_schedules',
                'ordering': ['schedule_date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'schedule_date'), name='unique_doctor_schedule_per_day'), models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='schedule_start_before_end')],
            },
        ),
    ]
