# Generated by Django 6.0.7 on 2026-07-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_backfill_and_relax_doctor_fields'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='doctorschedule',
            name='unique_doctor_schedule_per_day',
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctor', 'schedule_date', 'start_time', 'end_time'), name='unique_doctor_schedule_time_block'),
        ),
    ]
