# Generated by Django 6.0.7 on 2026-07-14 14:22

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(help_text='First name of the user.', max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Last name of the user.', max_length=30, verbose_name='Last name')),
                ('username', models.CharField(help_text='Username of the user.', max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(help_text='Email address of the user.', max_length=254, unique=True, verbose_name='Email address')),
                ('phone_number', models.CharField(help_text='Phone number of the user.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', help_text='Role of the user.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the user was last updated.')),
                ('last_login', models.DateTimeField(blank=True, help_text='Timestamp when the user last logged in.', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.\n                    A user will get all permissions granted to each of their groups.', related_name='user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='The permissions this user has. \n                    A user will get all permissions granted to each of their groups.', related_name='user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users_accounts',
                'ordering': ['first_name', 'last_name', '-created_at'],
                'indexes': [models.Index(fields=['username'], name='username_idx'), models.Index(fields=['email'], name='email_idx'), models.Index(fields=['phone_number'], name='phone_number_idx')],
                'constraints': [models.UniqueConstraint(fields=('username',), name='unique_username'), models.UniqueConstraint(fields=('email',), name='unique_email'), models.UniqueConstraint(fields=('phone_number',), name='unique_phone_number')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
