# Generated by Django 6.0.7 on 2026-07-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('patient_id', 'scheduled_at'), name='unique_patient_slot_when_booked'),
        ),
    ]
