# Generated by Django 6.0.7 on 2026-07-14 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='work_end_time',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Doctor working day end time.'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_start_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Doctor working day start time.'),
        ),
    ]
